version: "2"

run:
  build-tags:
    - kruda_stdjson

linters:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: transport/nethttp\.go
        linters:
          - errcheck
      - path: examples/
        linters:
          - errcheck
      - text: "QF"
        linters:
          - staticcheck
      - path: transport/wing/.*_stub\.go
        linters:
          - unused
