// Code generated by internal/bindgen; DO NOT EDIT.

package kruda

import (
	"reflect"
	"strconv"
	"strings"
)

func bindComposition10Input(c *Ctx) (reflect.Value, error) {
	input := new(composition10Input)
	input.ID = 7
	input.Page = 1
	input.Active = true
	input.Score = 1.5
	input.Name = "guest"
	input.ID2 = 7
	input.Page2 = 1
	input.Active2 = true
	input.Score2 = 1.5
	input.Name2 = "guest"
	var query0 string
	var query1 string
	var query2 string
	var query3 string
	var query4 string
	var query5 string
	var query6 string
	var query7 string
	var query8 string
	var query9 string
	queryRequest, queryBound := c.request.(interface{ bindingQuery() string })
	if queryBound {
		remaining := 10
		var seen0 bool
		var seen1 bool
		var seen2 bool
		var seen3 bool
		var seen4 bool
		var seen5 bool
		var seen6 bool
		var seen7 bool
		var seen8 bool
		var seen9 bool
		for query := queryRequest.bindingQuery(); query != "" && remaining > 0; {
			var pair string
			if amp := strings.IndexByte(query, '&'); amp >= 0 {
				pair, query = query[:amp], query[amp+1:]
			} else {
				pair, query = query, ""
			}
			if eq := strings.IndexByte(pair, '='); eq >= 0 {
				switch pair[:eq] {
				case "id":
					if !seen0 {
						query0 = pair[eq+1:]
						seen0 = true
						remaining--
					}
				case "page":
					if !seen1 {
						query1 = pair[eq+1:]
						seen1 = true
						remaining--
					}
				case "active":
					if !seen2 {
						query2 = pair[eq+1:]
						seen2 = true
						remaining--
					}
				case "score":
					if !seen3 {
						query3 = pair[eq+1:]
						seen3 = true
						remaining--
					}
				case "name":
					if !seen4 {
						query4 = pair[eq+1:]
						seen4 = true
						remaining--
					}
				case "id2":
					if !seen5 {
						query5 = pair[eq+1:]
						seen5 = true
						remaining--
					}
				case "page2":
					if !seen6 {
						query6 = pair[eq+1:]
						seen6 = true
						remaining--
					}
				case "active2":
					if !seen7 {
						query7 = pair[eq+1:]
						seen7 = true
						remaining--
					}
				case "score2":
					if !seen8 {
						query8 = pair[eq+1:]
						seen8 = true
						remaining--
					}
				case "name2":
					if !seen9 {
						query9 = pair[eq+1:]
						seen9 = true
						remaining--
					}
				}
			}
		}
	}
	{
		raw := query0
		if !queryBound {
			raw = c.Query("id")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id\": expected int64")
			}
			input.ID = int64(value)
		}
	}
	{
		raw := query1
		if !queryBound {
			raw = c.Query("page")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page\": expected int")
			}
			input.Page = int(value)
		}
	}
	{
		raw := query2
		if !queryBound {
			raw = c.Query("active")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active\": expected bool")
			}
			input.Active = bool(value)
		}
	}
	{
		raw := query3
		if !queryBound {
			raw = c.Query("score")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score\": expected float64")
			}
			input.Score = float64(value)
		}
	}
	{
		raw := query4
		if !queryBound {
			raw = c.Query("name")
		}
		if raw != "" {
			input.Name = raw
		}
	}
	{
		raw := query5
		if !queryBound {
			raw = c.Query("id2")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id2\": expected int64")
			}
			input.ID2 = int64(value)
		}
	}
	{
		raw := query6
		if !queryBound {
			raw = c.Query("page2")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page2\": expected int")
			}
			input.Page2 = int(value)
		}
	}
	{
		raw := query7
		if !queryBound {
			raw = c.Query("active2")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active2\": expected bool")
			}
			input.Active2 = bool(value)
		}
	}
	{
		raw := query8
		if !queryBound {
			raw = c.Query("score2")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score2\": expected float64")
			}
			input.Score2 = float64(value)
		}
	}
	{
		raw := query9
		if !queryBound {
			raw = c.Query("name2")
		}
		if raw != "" {
			input.Name2 = raw
		}
	}
	if raw := c.Param("id"); raw != "" {
		value, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return reflect.Value{}, BadRequest("invalid path parameter \"id\": expected int64")
		}
		input.ID = int64(value)
	}
	return reflect.ValueOf(input).Elem(), nil
}

func makeBindComposition10InputValidator(validators []fieldValidator) func(*composition10Input) bool {
	if len(validators) != 8 {
		return nil
	}
	inputType := reflect.TypeOf((*composition10Input)(nil)).Elem()
	// Compiled checks certify that these exact rules have no custom overrides.
	if inputType.NumField() <= 0 || inputType.Field(0).Name != "ID" || inputType.Field(0).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[0].index != 0 || validators[0].omitEmpty || len(validators[0].elemRules) != 0 || len(validators[0].rules) != 1 || len(validators[0].checks) != 1 {
		return nil
	}
	if validators[0].rules[0].name != "min" || validators[0].rules[0].param != "1" {
		return nil
	}
	if inputType.NumField() <= 1 || inputType.Field(1).Name != "Page" || inputType.Field(1).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[1].index != 1 || validators[1].omitEmpty || len(validators[1].elemRules) != 0 || len(validators[1].rules) != 2 || len(validators[1].checks) != 2 {
		return nil
	}
	if validators[1].rules[0].name != "min" || validators[1].rules[0].param != "1" {
		return nil
	}
	if validators[1].rules[1].name != "max" || validators[1].rules[1].param != "1000" {
		return nil
	}
	if inputType.NumField() <= 3 || inputType.Field(3).Name != "Score" || inputType.Field(3).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[2].index != 3 || validators[2].omitEmpty || len(validators[2].elemRules) != 0 || len(validators[2].rules) != 2 || len(validators[2].checks) != 2 {
		return nil
	}
	if validators[2].rules[0].name != "min" || validators[2].rules[0].param != "0" {
		return nil
	}
	if validators[2].rules[1].name != "max" || validators[2].rules[1].param != "100" {
		return nil
	}
	if inputType.NumField() <= 4 || inputType.Field(4).Name != "Name" || inputType.Field(4).Type.Kind() != reflect.String {
		return nil
	}
	if validators[3].index != 4 || validators[3].omitEmpty || len(validators[3].elemRules) != 0 || len(validators[3].rules) != 2 || len(validators[3].checks) != 2 {
		return nil
	}
	if validators[3].rules[0].name != "min" || validators[3].rules[0].param != "1" {
		return nil
	}
	if validators[3].rules[1].name != "max" || validators[3].rules[1].param != "64" {
		return nil
	}
	if inputType.NumField() <= 5 || inputType.Field(5).Name != "ID2" || inputType.Field(5).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[4].index != 5 || validators[4].omitEmpty || len(validators[4].elemRules) != 0 || len(validators[4].rules) != 1 || len(validators[4].checks) != 1 {
		return nil
	}
	if validators[4].rules[0].name != "min" || validators[4].rules[0].param != "1" {
		return nil
	}
	if inputType.NumField() <= 6 || inputType.Field(6).Name != "Page2" || inputType.Field(6).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[5].index != 6 || validators[5].omitEmpty || len(validators[5].elemRules) != 0 || len(validators[5].rules) != 2 || len(validators[5].checks) != 2 {
		return nil
	}
	if validators[5].rules[0].name != "min" || validators[5].rules[0].param != "1" {
		return nil
	}
	if validators[5].rules[1].name != "max" || validators[5].rules[1].param != "1000" {
		return nil
	}
	if inputType.NumField() <= 8 || inputType.Field(8).Name != "Score2" || inputType.Field(8).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[6].index != 8 || validators[6].omitEmpty || len(validators[6].elemRules) != 0 || len(validators[6].rules) != 2 || len(validators[6].checks) != 2 {
		return nil
	}
	if validators[6].rules[0].name != "min" || validators[6].rules[0].param != "0" {
		return nil
	}
	if validators[6].rules[1].name != "max" || validators[6].rules[1].param != "100" {
		return nil
	}
	if inputType.NumField() <= 9 || inputType.Field(9).Name != "Name2" || inputType.Field(9).Type.Kind() != reflect.String {
		return nil
	}
	if validators[7].index != 9 || validators[7].omitEmpty || len(validators[7].elemRules) != 0 || len(validators[7].rules) != 2 || len(validators[7].checks) != 2 {
		return nil
	}
	if validators[7].rules[0].name != "min" || validators[7].rules[0].param != "1" {
		return nil
	}
	if validators[7].rules[1].name != "max" || validators[7].rules[1].param != "64" {
		return nil
	}
	return func(input *composition10Input) bool {
		return int64(input.ID) >= 1 && int64(input.Page) >= 1 && int64(input.Page) <= 1000 && float64(input.Score) >= 0 && float64(input.Score) <= 100 && float64(len(input.Name)) >= 1 && float64(len(input.Name)) <= 64 && int64(input.ID2) >= 1 && int64(input.Page2) >= 1 && int64(input.Page2) <= 1000 && float64(input.Score2) >= 0 && float64(input.Score2) <= 100 && float64(len(input.Name2)) >= 1 && float64(len(input.Name2)) <= 64
	}
}
