// Code generated by cmd/bindgen; DO NOT EDIT.

package kruda

import (
	"reflect"
	"strconv"
	"strings"
)

func bindComposition5Input(c *Ctx) (reflect.Value, error) {
	input := new(composition5Input)
	input.ID = 7
	input.Page = 1
	input.Active = true
	input.Score = 1.5
	input.Name = "guest"
	var query0 string
	var query1 string
	var query2 string
	var query3 string
	var query4 string
	rawQuery, queryBound := c.RawQuery()
	if queryBound {
		remaining := 5
		var seen0 bool
		var seen1 bool
		var seen2 bool
		var seen3 bool
		var seen4 bool
		for query := rawQuery; query != "" && remaining > 0; {
			var pair string
			if amp := strings.IndexByte(query, '&'); amp >= 0 {
				pair, query = query[:amp], query[amp+1:]
			} else {
				pair, query = query, ""
			}
			if eq := strings.IndexByte(pair, '='); eq >= 0 {
				switch pair[:eq] {
				case "id":
					if !seen0 {
						query0 = pair[eq+1:]
						seen0 = true
						remaining--
					}
				case "page":
					if !seen1 {
						query1 = pair[eq+1:]
						seen1 = true
						remaining--
					}
				case "active":
					if !seen2 {
						query2 = pair[eq+1:]
						seen2 = true
						remaining--
					}
				case "score":
					if !seen3 {
						query3 = pair[eq+1:]
						seen3 = true
						remaining--
					}
				case "name":
					if !seen4 {
						query4 = pair[eq+1:]
						seen4 = true
						remaining--
					}
				}
			}
		}
	}
	{
		raw := query0
		if !queryBound {
			raw = c.Query("id")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id\": expected int64")
			}
			input.ID = int64(value)
		}
	}
	{
		raw := query1
		if !queryBound {
			raw = c.Query("page")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page\": expected int")
			}
			input.Page = int(value)
		}
	}
	{
		raw := query2
		if !queryBound {
			raw = c.Query("active")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active\": expected bool")
			}
			input.Active = bool(value)
		}
	}
	{
		raw := query3
		if !queryBound {
			raw = c.Query("score")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score\": expected float64")
			}
			input.Score = float64(value)
		}
	}
	{
		raw := query4
		if !queryBound {
			raw = c.Query("name")
		}
		if raw != "" {
			input.Name = raw
		}
	}
	if raw := c.Param("id"); raw != "" {
		value, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return reflect.Value{}, BadRequest("invalid path parameter \"id\": expected int64")
		}
		input.ID = int64(value)
	}
	return reflect.ValueOf(input).Elem(), nil
}

func makeBindComposition5InputValidator(validators []ValidatorDescriptor) func(*composition5Input) bool {
	if len(validators) != 4 {
		return nil
	}
	inputType := reflect.TypeOf((*composition5Input)(nil)).Elem()
	// Compiled checks certify that these exact rules have no custom overrides.
	if inputType.NumField() <= 0 || inputType.Field(0).Name != "ID" || inputType.Field(0).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[0].Index != 0 || validators[0].OmitEmpty || validators[0].NumElemRules != 0 || len(validators[0].Rules) != 1 || validators[0].NumChecks != 1 {
		return nil
	}
	if validators[0].Rules[0].Name != "min" || validators[0].Rules[0].Param != "1" {
		return nil
	}
	if inputType.NumField() <= 1 || inputType.Field(1).Name != "Page" || inputType.Field(1).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[1].Index != 1 || validators[1].OmitEmpty || validators[1].NumElemRules != 0 || len(validators[1].Rules) != 2 || validators[1].NumChecks != 2 {
		return nil
	}
	if validators[1].Rules[0].Name != "min" || validators[1].Rules[0].Param != "1" {
		return nil
	}
	if validators[1].Rules[1].Name != "max" || validators[1].Rules[1].Param != "1000" {
		return nil
	}
	if inputType.NumField() <= 3 || inputType.Field(3).Name != "Score" || inputType.Field(3).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[2].Index != 3 || validators[2].OmitEmpty || validators[2].NumElemRules != 0 || len(validators[2].Rules) != 2 || validators[2].NumChecks != 2 {
		return nil
	}
	if validators[2].Rules[0].Name != "min" || validators[2].Rules[0].Param != "0" {
		return nil
	}
	if validators[2].Rules[1].Name != "max" || validators[2].Rules[1].Param != "100" {
		return nil
	}
	if inputType.NumField() <= 4 || inputType.Field(4).Name != "Name" || inputType.Field(4).Type.Kind() != reflect.String {
		return nil
	}
	if validators[3].Index != 4 || validators[3].OmitEmpty || validators[3].NumElemRules != 0 || len(validators[3].Rules) != 2 || validators[3].NumChecks != 2 {
		return nil
	}
	if validators[3].Rules[0].Name != "min" || validators[3].Rules[0].Param != "1" {
		return nil
	}
	if validators[3].Rules[1].Name != "max" || validators[3].Rules[1].Param != "64" {
		return nil
	}
	return func(input *composition5Input) bool {
		return int64(input.ID) >= 1 && int64(input.Page) >= 1 && int64(input.Page) <= 1000 && float64(input.Score) >= 0 && float64(input.Score) <= 100 && float64(len(input.Name)) >= 1 && float64(len(input.Name)) <= 64
	}
}

var bindComposition5InputShape = BinderShape{NumFields: 5, Fields: []BinderFieldShape{
	{Name: "ID", Exported: true, Kind: "int64", Query: "id", Param: "id", Default: "7"},
	{Name: "Page", Exported: true, Kind: "int", Query: "page", Param: "", Default: "1"},
	{Name: "Active", Exported: true, Kind: "bool", Query: "active", Param: "", Default: "true"},
	{Name: "Score", Exported: true, Kind: "float64", Query: "score", Param: "", Default: "1.5"},
	{Name: "Name", Exported: true, Kind: "string", Query: "name", Param: "", Default: "guest"},
}}

func bindComposition5InputAttested() func(*Ctx) (reflect.Value, error) {
	if !AttestBinderShape[composition5Input](bindComposition5InputShape) {
		return nil
	}
	return bindComposition5Input
}

func composition5InputPlan() GeneratedPlan[composition5Input] {
	return GeneratedPlan[composition5Input]{Shape: bindComposition5InputShape, Binder: bindComposition5InputAttested(), ValidatorFactory: makeBindComposition5InputValidator}
}
