// Code generated by cmd/bindgen; DO NOT EDIT.

package kruda

import (
	"reflect"
	"strconv"
	"strings"
)

func bindComposition30Input(c *Ctx) (reflect.Value, error) {
	input := new(composition30Input)
	input.ID = 7
	input.Page = 1
	input.Active = true
	input.Score = 1.5
	input.Name = "guest"
	input.ID2 = 7
	input.Page2 = 1
	input.Active2 = true
	input.Score2 = 1.5
	input.Name2 = "guest"
	input.ID3 = 7
	input.Page3 = 1
	input.Active3 = true
	input.Score3 = 1.5
	input.Name3 = "guest"
	input.ID4 = 7
	input.Page4 = 1
	input.Active4 = true
	input.Score4 = 1.5
	input.Name4 = "guest"
	input.ID5 = 7
	input.Page5 = 1
	input.Active5 = true
	input.Score5 = 1.5
	input.Name5 = "guest"
	input.ID6 = 7
	input.Page6 = 1
	input.Active6 = true
	input.Score6 = 1.5
	input.Name6 = "guest"
	var query0 string
	var query1 string
	var query2 string
	var query3 string
	var query4 string
	var query5 string
	var query6 string
	var query7 string
	var query8 string
	var query9 string
	var query10 string
	var query11 string
	var query12 string
	var query13 string
	var query14 string
	var query15 string
	var query16 string
	var query17 string
	var query18 string
	var query19 string
	var query20 string
	var query21 string
	var query22 string
	var query23 string
	var query24 string
	var query25 string
	var query26 string
	var query27 string
	var query28 string
	var query29 string
	rawQuery, queryBound := c.RawQuery()
	if queryBound {
		remaining := 30
		var seen0 bool
		var seen1 bool
		var seen2 bool
		var seen3 bool
		var seen4 bool
		var seen5 bool
		var seen6 bool
		var seen7 bool
		var seen8 bool
		var seen9 bool
		var seen10 bool
		var seen11 bool
		var seen12 bool
		var seen13 bool
		var seen14 bool
		var seen15 bool
		var seen16 bool
		var seen17 bool
		var seen18 bool
		var seen19 bool
		var seen20 bool
		var seen21 bool
		var seen22 bool
		var seen23 bool
		var seen24 bool
		var seen25 bool
		var seen26 bool
		var seen27 bool
		var seen28 bool
		var seen29 bool
		for query := rawQuery; query != "" && remaining > 0; {
			var pair string
			if amp := strings.IndexByte(query, '&'); amp >= 0 {
				pair, query = query[:amp], query[amp+1:]
			} else {
				pair, query = query, ""
			}
			if eq := strings.IndexByte(pair, '='); eq >= 0 {
				switch pair[:eq] {
				case "id":
					if !seen0 {
						query0 = pair[eq+1:]
						seen0 = true
						remaining--
					}
				case "page":
					if !seen1 {
						query1 = pair[eq+1:]
						seen1 = true
						remaining--
					}
				case "active":
					if !seen2 {
						query2 = pair[eq+1:]
						seen2 = true
						remaining--
					}
				case "score":
					if !seen3 {
						query3 = pair[eq+1:]
						seen3 = true
						remaining--
					}
				case "name":
					if !seen4 {
						query4 = pair[eq+1:]
						seen4 = true
						remaining--
					}
				case "id2":
					if !seen5 {
						query5 = pair[eq+1:]
						seen5 = true
						remaining--
					}
				case "page2":
					if !seen6 {
						query6 = pair[eq+1:]
						seen6 = true
						remaining--
					}
				case "active2":
					if !seen7 {
						query7 = pair[eq+1:]
						seen7 = true
						remaining--
					}
				case "score2":
					if !seen8 {
						query8 = pair[eq+1:]
						seen8 = true
						remaining--
					}
				case "name2":
					if !seen9 {
						query9 = pair[eq+1:]
						seen9 = true
						remaining--
					}
				case "id3":
					if !seen10 {
						query10 = pair[eq+1:]
						seen10 = true
						remaining--
					}
				case "page3":
					if !seen11 {
						query11 = pair[eq+1:]
						seen11 = true
						remaining--
					}
				case "active3":
					if !seen12 {
						query12 = pair[eq+1:]
						seen12 = true
						remaining--
					}
				case "score3":
					if !seen13 {
						query13 = pair[eq+1:]
						seen13 = true
						remaining--
					}
				case "name3":
					if !seen14 {
						query14 = pair[eq+1:]
						seen14 = true
						remaining--
					}
				case "id4":
					if !seen15 {
						query15 = pair[eq+1:]
						seen15 = true
						remaining--
					}
				case "page4":
					if !seen16 {
						query16 = pair[eq+1:]
						seen16 = true
						remaining--
					}
				case "active4":
					if !seen17 {
						query17 = pair[eq+1:]
						seen17 = true
						remaining--
					}
				case "score4":
					if !seen18 {
						query18 = pair[eq+1:]
						seen18 = true
						remaining--
					}
				case "name4":
					if !seen19 {
						query19 = pair[eq+1:]
						seen19 = true
						remaining--
					}
				case "id5":
					if !seen20 {
						query20 = pair[eq+1:]
						seen20 = true
						remaining--
					}
				case "page5":
					if !seen21 {
						query21 = pair[eq+1:]
						seen21 = true
						remaining--
					}
				case "active5":
					if !seen22 {
						query22 = pair[eq+1:]
						seen22 = true
						remaining--
					}
				case "score5":
					if !seen23 {
						query23 = pair[eq+1:]
						seen23 = true
						remaining--
					}
				case "name5":
					if !seen24 {
						query24 = pair[eq+1:]
						seen24 = true
						remaining--
					}
				case "id6":
					if !seen25 {
						query25 = pair[eq+1:]
						seen25 = true
						remaining--
					}
				case "page6":
					if !seen26 {
						query26 = pair[eq+1:]
						seen26 = true
						remaining--
					}
				case "active6":
					if !seen27 {
						query27 = pair[eq+1:]
						seen27 = true
						remaining--
					}
				case "score6":
					if !seen28 {
						query28 = pair[eq+1:]
						seen28 = true
						remaining--
					}
				case "name6":
					if !seen29 {
						query29 = pair[eq+1:]
						seen29 = true
						remaining--
					}
				}
			}
		}
	}
	{
		raw := query0
		if !queryBound {
			raw = c.Query("id")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id\": expected int64")
			}
			input.ID = int64(value)
		}
	}
	{
		raw := query1
		if !queryBound {
			raw = c.Query("page")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page\": expected int")
			}
			input.Page = int(value)
		}
	}
	{
		raw := query2
		if !queryBound {
			raw = c.Query("active")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active\": expected bool")
			}
			input.Active = bool(value)
		}
	}
	{
		raw := query3
		if !queryBound {
			raw = c.Query("score")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score\": expected float64")
			}
			input.Score = float64(value)
		}
	}
	{
		raw := query4
		if !queryBound {
			raw = c.Query("name")
		}
		if raw != "" {
			input.Name = raw
		}
	}
	{
		raw := query5
		if !queryBound {
			raw = c.Query("id2")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id2\": expected int64")
			}
			input.ID2 = int64(value)
		}
	}
	{
		raw := query6
		if !queryBound {
			raw = c.Query("page2")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page2\": expected int")
			}
			input.Page2 = int(value)
		}
	}
	{
		raw := query7
		if !queryBound {
			raw = c.Query("active2")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active2\": expected bool")
			}
			input.Active2 = bool(value)
		}
	}
	{
		raw := query8
		if !queryBound {
			raw = c.Query("score2")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score2\": expected float64")
			}
			input.Score2 = float64(value)
		}
	}
	{
		raw := query9
		if !queryBound {
			raw = c.Query("name2")
		}
		if raw != "" {
			input.Name2 = raw
		}
	}
	{
		raw := query10
		if !queryBound {
			raw = c.Query("id3")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id3\": expected int64")
			}
			input.ID3 = int64(value)
		}
	}
	{
		raw := query11
		if !queryBound {
			raw = c.Query("page3")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page3\": expected int")
			}
			input.Page3 = int(value)
		}
	}
	{
		raw := query12
		if !queryBound {
			raw = c.Query("active3")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active3\": expected bool")
			}
			input.Active3 = bool(value)
		}
	}
	{
		raw := query13
		if !queryBound {
			raw = c.Query("score3")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score3\": expected float64")
			}
			input.Score3 = float64(value)
		}
	}
	{
		raw := query14
		if !queryBound {
			raw = c.Query("name3")
		}
		if raw != "" {
			input.Name3 = raw
		}
	}
	{
		raw := query15
		if !queryBound {
			raw = c.Query("id4")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id4\": expected int64")
			}
			input.ID4 = int64(value)
		}
	}
	{
		raw := query16
		if !queryBound {
			raw = c.Query("page4")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page4\": expected int")
			}
			input.Page4 = int(value)
		}
	}
	{
		raw := query17
		if !queryBound {
			raw = c.Query("active4")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active4\": expected bool")
			}
			input.Active4 = bool(value)
		}
	}
	{
		raw := query18
		if !queryBound {
			raw = c.Query("score4")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score4\": expected float64")
			}
			input.Score4 = float64(value)
		}
	}
	{
		raw := query19
		if !queryBound {
			raw = c.Query("name4")
		}
		if raw != "" {
			input.Name4 = raw
		}
	}
	{
		raw := query20
		if !queryBound {
			raw = c.Query("id5")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id5\": expected int64")
			}
			input.ID5 = int64(value)
		}
	}
	{
		raw := query21
		if !queryBound {
			raw = c.Query("page5")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page5\": expected int")
			}
			input.Page5 = int(value)
		}
	}
	{
		raw := query22
		if !queryBound {
			raw = c.Query("active5")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active5\": expected bool")
			}
			input.Active5 = bool(value)
		}
	}
	{
		raw := query23
		if !queryBound {
			raw = c.Query("score5")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score5\": expected float64")
			}
			input.Score5 = float64(value)
		}
	}
	{
		raw := query24
		if !queryBound {
			raw = c.Query("name5")
		}
		if raw != "" {
			input.Name5 = raw
		}
	}
	{
		raw := query25
		if !queryBound {
			raw = c.Query("id6")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"id6\": expected int64")
			}
			input.ID6 = int64(value)
		}
	}
	{
		raw := query26
		if !queryBound {
			raw = c.Query("page6")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"page6\": expected int")
			}
			input.Page6 = int(value)
		}
	}
	{
		raw := query27
		if !queryBound {
			raw = c.Query("active6")
		}
		if raw != "" {
			value, err := strconv.ParseBool(raw)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"active6\": expected bool")
			}
			input.Active6 = bool(value)
		}
	}
	{
		raw := query28
		if !queryBound {
			raw = c.Query("score6")
		}
		if raw != "" {
			value, err := strconv.ParseFloat(raw, 64)
			if err != nil {
				return reflect.Value{}, BadRequest("invalid query parameter \"score6\": expected float64")
			}
			input.Score6 = float64(value)
		}
	}
	{
		raw := query29
		if !queryBound {
			raw = c.Query("name6")
		}
		if raw != "" {
			input.Name6 = raw
		}
	}
	if raw := c.Param("id"); raw != "" {
		value, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return reflect.Value{}, BadRequest("invalid path parameter \"id\": expected int64")
		}
		input.ID = int64(value)
	}
	return reflect.ValueOf(input).Elem(), nil
}

func makeBindComposition30InputValidator(validators []ValidatorDescriptor) func(*composition30Input) bool {
	if len(validators) != 24 {
		return nil
	}
	inputType := reflect.TypeOf((*composition30Input)(nil)).Elem()
	// Compiled checks certify that these exact rules have no custom overrides.
	if inputType.NumField() <= 0 || inputType.Field(0).Name != "ID" || inputType.Field(0).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[0].Index != 0 || validators[0].OmitEmpty || validators[0].NumElemRules != 0 || len(validators[0].Rules) != 1 || validators[0].NumChecks != 1 {
		return nil
	}
	if validators[0].Rules[0].Name != "min" || validators[0].Rules[0].Param != "1" {
		return nil
	}
	if inputType.NumField() <= 1 || inputType.Field(1).Name != "Page" || inputType.Field(1).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[1].Index != 1 || validators[1].OmitEmpty || validators[1].NumElemRules != 0 || len(validators[1].Rules) != 2 || validators[1].NumChecks != 2 {
		return nil
	}
	if validators[1].Rules[0].Name != "min" || validators[1].Rules[0].Param != "1" {
		return nil
	}
	if validators[1].Rules[1].Name != "max" || validators[1].Rules[1].Param != "1000" {
		return nil
	}
	if inputType.NumField() <= 3 || inputType.Field(3).Name != "Score" || inputType.Field(3).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[2].Index != 3 || validators[2].OmitEmpty || validators[2].NumElemRules != 0 || len(validators[2].Rules) != 2 || validators[2].NumChecks != 2 {
		return nil
	}
	if validators[2].Rules[0].Name != "min" || validators[2].Rules[0].Param != "0" {
		return nil
	}
	if validators[2].Rules[1].Name != "max" || validators[2].Rules[1].Param != "100" {
		return nil
	}
	if inputType.NumField() <= 4 || inputType.Field(4).Name != "Name" || inputType.Field(4).Type.Kind() != reflect.String {
		return nil
	}
	if validators[3].Index != 4 || validators[3].OmitEmpty || validators[3].NumElemRules != 0 || len(validators[3].Rules) != 2 || validators[3].NumChecks != 2 {
		return nil
	}
	if validators[3].Rules[0].Name != "min" || validators[3].Rules[0].Param != "1" {
		return nil
	}
	if validators[3].Rules[1].Name != "max" || validators[3].Rules[1].Param != "64" {
		return nil
	}
	if inputType.NumField() <= 5 || inputType.Field(5).Name != "ID2" || inputType.Field(5).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[4].Index != 5 || validators[4].OmitEmpty || validators[4].NumElemRules != 0 || len(validators[4].Rules) != 1 || validators[4].NumChecks != 1 {
		return nil
	}
	if validators[4].Rules[0].Name != "min" || validators[4].Rules[0].Param != "1" {
		return nil
	}
	if inputType.NumField() <= 6 || inputType.Field(6).Name != "Page2" || inputType.Field(6).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[5].Index != 6 || validators[5].OmitEmpty || validators[5].NumElemRules != 0 || len(validators[5].Rules) != 2 || validators[5].NumChecks != 2 {
		return nil
	}
	if validators[5].Rules[0].Name != "min" || validators[5].Rules[0].Param != "1" {
		return nil
	}
	if validators[5].Rules[1].Name != "max" || validators[5].Rules[1].Param != "1000" {
		return nil
	}
	if inputType.NumField() <= 8 || inputType.Field(8).Name != "Score2" || inputType.Field(8).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[6].Index != 8 || validators[6].OmitEmpty || validators[6].NumElemRules != 0 || len(validators[6].Rules) != 2 || validators[6].NumChecks != 2 {
		return nil
	}
	if validators[6].Rules[0].Name != "min" || validators[6].Rules[0].Param != "0" {
		return nil
	}
	if validators[6].Rules[1].Name != "max" || validators[6].Rules[1].Param != "100" {
		return nil
	}
	if inputType.NumField() <= 9 || inputType.Field(9).Name != "Name2" || inputType.Field(9).Type.Kind() != reflect.String {
		return nil
	}
	if validators[7].Index != 9 || validators[7].OmitEmpty || validators[7].NumElemRules != 0 || len(validators[7].Rules) != 2 || validators[7].NumChecks != 2 {
		return nil
	}
	if validators[7].Rules[0].Name != "min" || validators[7].Rules[0].Param != "1" {
		return nil
	}
	if validators[7].Rules[1].Name != "max" || validators[7].Rules[1].Param != "64" {
		return nil
	}
	if inputType.NumField() <= 10 || inputType.Field(10).Name != "ID3" || inputType.Field(10).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[8].Index != 10 || validators[8].OmitEmpty || validators[8].NumElemRules != 0 || len(validators[8].Rules) != 1 || validators[8].NumChecks != 1 {
		return nil
	}
	if validators[8].Rules[0].Name != "min" || validators[8].Rules[0].Param != "1" {
		return nil
	}
	if inputType.NumField() <= 11 || inputType.Field(11).Name != "Page3" || inputType.Field(11).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[9].Index != 11 || validators[9].OmitEmpty || validators[9].NumElemRules != 0 || len(validators[9].Rules) != 2 || validators[9].NumChecks != 2 {
		return nil
	}
	if validators[9].Rules[0].Name != "min" || validators[9].Rules[0].Param != "1" {
		return nil
	}
	if validators[9].Rules[1].Name != "max" || validators[9].Rules[1].Param != "1000" {
		return nil
	}
	if inputType.NumField() <= 13 || inputType.Field(13).Name != "Score3" || inputType.Field(13).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[10].Index != 13 || validators[10].OmitEmpty || validators[10].NumElemRules != 0 || len(validators[10].Rules) != 2 || validators[10].NumChecks != 2 {
		return nil
	}
	if validators[10].Rules[0].Name != "min" || validators[10].Rules[0].Param != "0" {
		return nil
	}
	if validators[10].Rules[1].Name != "max" || validators[10].Rules[1].Param != "100" {
		return nil
	}
	if inputType.NumField() <= 14 || inputType.Field(14).Name != "Name3" || inputType.Field(14).Type.Kind() != reflect.String {
		return nil
	}
	if validators[11].Index != 14 || validators[11].OmitEmpty || validators[11].NumElemRules != 0 || len(validators[11].Rules) != 2 || validators[11].NumChecks != 2 {
		return nil
	}
	if validators[11].Rules[0].Name != "min" || validators[11].Rules[0].Param != "1" {
		return nil
	}
	if validators[11].Rules[1].Name != "max" || validators[11].Rules[1].Param != "64" {
		return nil
	}
	if inputType.NumField() <= 15 || inputType.Field(15).Name != "ID4" || inputType.Field(15).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[12].Index != 15 || validators[12].OmitEmpty || validators[12].NumElemRules != 0 || len(validators[12].Rules) != 1 || validators[12].NumChecks != 1 {
		return nil
	}
	if validators[12].Rules[0].Name != "min" || validators[12].Rules[0].Param != "1" {
		return nil
	}
	if inputType.NumField() <= 16 || inputType.Field(16).Name != "Page4" || inputType.Field(16).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[13].Index != 16 || validators[13].OmitEmpty || validators[13].NumElemRules != 0 || len(validators[13].Rules) != 2 || validators[13].NumChecks != 2 {
		return nil
	}
	if validators[13].Rules[0].Name != "min" || validators[13].Rules[0].Param != "1" {
		return nil
	}
	if validators[13].Rules[1].Name != "max" || validators[13].Rules[1].Param != "1000" {
		return nil
	}
	if inputType.NumField() <= 18 || inputType.Field(18).Name != "Score4" || inputType.Field(18).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[14].Index != 18 || validators[14].OmitEmpty || validators[14].NumElemRules != 0 || len(validators[14].Rules) != 2 || validators[14].NumChecks != 2 {
		return nil
	}
	if validators[14].Rules[0].Name != "min" || validators[14].Rules[0].Param != "0" {
		return nil
	}
	if validators[14].Rules[1].Name != "max" || validators[14].Rules[1].Param != "100" {
		return nil
	}
	if inputType.NumField() <= 19 || inputType.Field(19).Name != "Name4" || inputType.Field(19).Type.Kind() != reflect.String {
		return nil
	}
	if validators[15].Index != 19 || validators[15].OmitEmpty || validators[15].NumElemRules != 0 || len(validators[15].Rules) != 2 || validators[15].NumChecks != 2 {
		return nil
	}
	if validators[15].Rules[0].Name != "min" || validators[15].Rules[0].Param != "1" {
		return nil
	}
	if validators[15].Rules[1].Name != "max" || validators[15].Rules[1].Param != "64" {
		return nil
	}
	if inputType.NumField() <= 20 || inputType.Field(20).Name != "ID5" || inputType.Field(20).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[16].Index != 20 || validators[16].OmitEmpty || validators[16].NumElemRules != 0 || len(validators[16].Rules) != 1 || validators[16].NumChecks != 1 {
		return nil
	}
	if validators[16].Rules[0].Name != "min" || validators[16].Rules[0].Param != "1" {
		return nil
	}
	if inputType.NumField() <= 21 || inputType.Field(21).Name != "Page5" || inputType.Field(21).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[17].Index != 21 || validators[17].OmitEmpty || validators[17].NumElemRules != 0 || len(validators[17].Rules) != 2 || validators[17].NumChecks != 2 {
		return nil
	}
	if validators[17].Rules[0].Name != "min" || validators[17].Rules[0].Param != "1" {
		return nil
	}
	if validators[17].Rules[1].Name != "max" || validators[17].Rules[1].Param != "1000" {
		return nil
	}
	if inputType.NumField() <= 23 || inputType.Field(23).Name != "Score5" || inputType.Field(23).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[18].Index != 23 || validators[18].OmitEmpty || validators[18].NumElemRules != 0 || len(validators[18].Rules) != 2 || validators[18].NumChecks != 2 {
		return nil
	}
	if validators[18].Rules[0].Name != "min" || validators[18].Rules[0].Param != "0" {
		return nil
	}
	if validators[18].Rules[1].Name != "max" || validators[18].Rules[1].Param != "100" {
		return nil
	}
	if inputType.NumField() <= 24 || inputType.Field(24).Name != "Name5" || inputType.Field(24).Type.Kind() != reflect.String {
		return nil
	}
	if validators[19].Index != 24 || validators[19].OmitEmpty || validators[19].NumElemRules != 0 || len(validators[19].Rules) != 2 || validators[19].NumChecks != 2 {
		return nil
	}
	if validators[19].Rules[0].Name != "min" || validators[19].Rules[0].Param != "1" {
		return nil
	}
	if validators[19].Rules[1].Name != "max" || validators[19].Rules[1].Param != "64" {
		return nil
	}
	if inputType.NumField() <= 25 || inputType.Field(25).Name != "ID6" || inputType.Field(25).Type.Kind() != reflect.Int64 {
		return nil
	}
	if validators[20].Index != 25 || validators[20].OmitEmpty || validators[20].NumElemRules != 0 || len(validators[20].Rules) != 1 || validators[20].NumChecks != 1 {
		return nil
	}
	if validators[20].Rules[0].Name != "min" || validators[20].Rules[0].Param != "1" {
		return nil
	}
	if inputType.NumField() <= 26 || inputType.Field(26).Name != "Page6" || inputType.Field(26).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[21].Index != 26 || validators[21].OmitEmpty || validators[21].NumElemRules != 0 || len(validators[21].Rules) != 2 || validators[21].NumChecks != 2 {
		return nil
	}
	if validators[21].Rules[0].Name != "min" || validators[21].Rules[0].Param != "1" {
		return nil
	}
	if validators[21].Rules[1].Name != "max" || validators[21].Rules[1].Param != "1000" {
		return nil
	}
	if inputType.NumField() <= 28 || inputType.Field(28).Name != "Score6" || inputType.Field(28).Type.Kind() != reflect.Float64 {
		return nil
	}
	if validators[22].Index != 28 || validators[22].OmitEmpty || validators[22].NumElemRules != 0 || len(validators[22].Rules) != 2 || validators[22].NumChecks != 2 {
		return nil
	}
	if validators[22].Rules[0].Name != "min" || validators[22].Rules[0].Param != "0" {
		return nil
	}
	if validators[22].Rules[1].Name != "max" || validators[22].Rules[1].Param != "100" {
		return nil
	}
	if inputType.NumField() <= 29 || inputType.Field(29).Name != "Name6" || inputType.Field(29).Type.Kind() != reflect.String {
		return nil
	}
	if validators[23].Index != 29 || validators[23].OmitEmpty || validators[23].NumElemRules != 0 || len(validators[23].Rules) != 2 || validators[23].NumChecks != 2 {
		return nil
	}
	if validators[23].Rules[0].Name != "min" || validators[23].Rules[0].Param != "1" {
		return nil
	}
	if validators[23].Rules[1].Name != "max" || validators[23].Rules[1].Param != "64" {
		return nil
	}
	return func(input *composition30Input) bool {
		return int64(input.ID) >= 1 && int64(input.Page) >= 1 && int64(input.Page) <= 1000 && float64(input.Score) >= 0 && float64(input.Score) <= 100 && float64(len(input.Name)) >= 1 && float64(len(input.Name)) <= 64 && int64(input.ID2) >= 1 && int64(input.Page2) >= 1 && int64(input.Page2) <= 1000 && float64(input.Score2) >= 0 && float64(input.Score2) <= 100 && float64(len(input.Name2)) >= 1 && float64(len(input.Name2)) <= 64 && int64(input.ID3) >= 1 && int64(input.Page3) >= 1 && int64(input.Page3) <= 1000 && float64(input.Score3) >= 0 && float64(input.Score3) <= 100 && float64(len(input.Name3)) >= 1 && float64(len(input.Name3)) <= 64 && int64(input.ID4) >= 1 && int64(input.Page4) >= 1 && int64(input.Page4) <= 1000 && float64(input.Score4) >= 0 && float64(input.Score4) <= 100 && float64(len(input.Name4)) >= 1 && float64(len(input.Name4)) <= 64 && int64(input.ID5) >= 1 && int64(input.Page5) >= 1 && int64(input.Page5) <= 1000 && float64(input.Score5) >= 0 && float64(input.Score5) <= 100 && float64(len(input.Name5)) >= 1 && float64(len(input.Name5)) <= 64 && int64(input.ID6) >= 1 && int64(input.Page6) >= 1 && int64(input.Page6) <= 1000 && float64(input.Score6) >= 0 && float64(input.Score6) <= 100 && float64(len(input.Name6)) >= 1 && float64(len(input.Name6)) <= 64
	}
}

var bindComposition30InputShape = BinderShape{NumFields: 30, Fields: []BinderFieldShape{
	{Name: "ID", Exported: true, Kind: "int64", Query: "id", Param: "id", Default: "7"},
	{Name: "Page", Exported: true, Kind: "int", Query: "page", Param: "", Default: "1"},
	{Name: "Active", Exported: true, Kind: "bool", Query: "active", Param: "", Default: "true"},
	{Name: "Score", Exported: true, Kind: "float64", Query: "score", Param: "", Default: "1.5"},
	{Name: "Name", Exported: true, Kind: "string", Query: "name", Param: "", Default: "guest"},
	{Name: "ID2", Exported: true, Kind: "int64", Query: "id2", Param: "", Default: "7"},
	{Name: "Page2", Exported: true, Kind: "int", Query: "page2", Param: "", Default: "1"},
	{Name: "Active2", Exported: true, Kind: "bool", Query: "active2", Param: "", Default: "true"},
	{Name: "Score2", Exported: true, Kind: "float64", Query: "score2", Param: "", Default: "1.5"},
	{Name: "Name2", Exported: true, Kind: "string", Query: "name2", Param: "", Default: "guest"},
	{Name: "ID3", Exported: true, Kind: "int64", Query: "id3", Param: "", Default: "7"},
	{Name: "Page3", Exported: true, Kind: "int", Query: "page3", Param: "", Default: "1"},
	{Name: "Active3", Exported: true, Kind: "bool", Query: "active3", Param: "", Default: "true"},
	{Name: "Score3", Exported: true, Kind: "float64", Query: "score3", Param: "", Default: "1.5"},
	{Name: "Name3", Exported: true, Kind: "string", Query: "name3", Param: "", Default: "guest"},
	{Name: "ID4", Exported: true, Kind: "int64", Query: "id4", Param: "", Default: "7"},
	{Name: "Page4", Exported: true, Kind: "int", Query: "page4", Param: "", Default: "1"},
	{Name: "Active4", Exported: true, Kind: "bool", Query: "active4", Param: "", Default: "true"},
	{Name: "Score4", Exported: true, Kind: "float64", Query: "score4", Param: "", Default: "1.5"},
	{Name: "Name4", Exported: true, Kind: "string", Query: "name4", Param: "", Default: "guest"},
	{Name: "ID5", Exported: true, Kind: "int64", Query: "id5", Param: "", Default: "7"},
	{Name: "Page5", Exported: true, Kind: "int", Query: "page5", Param: "", Default: "1"},
	{Name: "Active5", Exported: true, Kind: "bool", Query: "active5", Param: "", Default: "true"},
	{Name: "Score5", Exported: true, Kind: "float64", Query: "score5", Param: "", Default: "1.5"},
	{Name: "Name5", Exported: true, Kind: "string", Query: "name5", Param: "", Default: "guest"},
	{Name: "ID6", Exported: true, Kind: "int64", Query: "id6", Param: "", Default: "7"},
	{Name: "Page6", Exported: true, Kind: "int", Query: "page6", Param: "", Default: "1"},
	{Name: "Active6", Exported: true, Kind: "bool", Query: "active6", Param: "", Default: "true"},
	{Name: "Score6", Exported: true, Kind: "float64", Query: "score6", Param: "", Default: "1.5"},
	{Name: "Name6", Exported: true, Kind: "string", Query: "name6", Param: "", Default: "guest"},
}}

func bindComposition30InputAttested() func(*Ctx) (reflect.Value, error) {
	if !AttestBinderShape[composition30Input](bindComposition30InputShape) {
		return nil
	}
	return bindComposition30Input
}

func composition30InputPlan() GeneratedPlan[composition30Input] {
	return GeneratedPlan[composition30Input]{Shape: bindComposition30InputShape, Binder: bindComposition30InputAttested(), ValidatorFactory: makeBindComposition30InputValidator}
}
