// Code generated by internal/bindgen; DO NOT EDIT.

package externalbind

import (
	"github.com/go-kruda/kruda"
	"reflect"
	"strconv"
	"strings"
)

func bindSearchInput(c *kruda.Ctx) (reflect.Value, error) {
	input := new(searchInput)
	input.Q = "all"
	input.Page = 1
	var query0 string
	var query1 string
	rawQuery, queryBound := c.RawQuery()
	if queryBound {
		remaining := 2
		var seen0 bool
		var seen1 bool
		for query := rawQuery; query != "" && remaining > 0; {
			var pair string
			if amp := strings.IndexByte(query, '&'); amp >= 0 {
				pair, query = query[:amp], query[amp+1:]
			} else {
				pair, query = query, ""
			}
			if eq := strings.IndexByte(pair, '='); eq >= 0 {
				switch pair[:eq] {
				case "q":
					if !seen0 {
						query0 = pair[eq+1:]
						seen0 = true
						remaining--
					}
				case "page":
					if !seen1 {
						query1 = pair[eq+1:]
						seen1 = true
						remaining--
					}
				}
			}
		}
	}
	{
		raw := query0
		if !queryBound {
			raw = c.Query("q")
		}
		if raw != "" {
			input.Q = raw
		}
	}
	{
		raw := query1
		if !queryBound {
			raw = c.Query("page")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, kruda.BadRequest("invalid query parameter \"page\": expected int")
			}
			input.Page = int(value)
		}
	}
	return reflect.ValueOf(input).Elem(), nil
}

var bindSearchInputShape = kruda.BinderShape{NumFields: 2, Fields: []kruda.BinderFieldShape{
	{Name: "Q", Exported: true, Kind: "string", Query: "q", Param: "", Default: "all"},
	{Name: "Page", Exported: true, Kind: "int", Query: "page", Param: "", Default: "1"},
}}

func bindSearchInputAttested() func(*kruda.Ctx) (reflect.Value, error) {
	if !kruda.AttestBinderShape[searchInput](bindSearchInputShape) {
		return nil
	}
	return bindSearchInput
}
