// Code generated by cmd/bindgen; DO NOT EDIT.

package externalbind

import (
	"github.com/go-kruda/kruda"
	"reflect"
	"strconv"
	"strings"
)

func bindSearchInput(c *kruda.Ctx) (reflect.Value, error) {
	input := new(searchInput)
	input.Q = "all"
	input.Page = 1
	var query0 string
	var query1 string
	rawQuery, queryBound := c.RawQuery()
	if queryBound {
		remaining := 2
		var seen0 bool
		var seen1 bool
		for query := rawQuery; query != "" && remaining > 0; {
			var pair string
			if amp := strings.IndexByte(query, '&'); amp >= 0 {
				pair, query = query[:amp], query[amp+1:]
			} else {
				pair, query = query, ""
			}
			if eq := strings.IndexByte(pair, '='); eq >= 0 {
				switch pair[:eq] {
				case "q":
					if !seen0 {
						query0 = pair[eq+1:]
						seen0 = true
						remaining--
					}
				case "page":
					if !seen1 {
						query1 = pair[eq+1:]
						seen1 = true
						remaining--
					}
				}
			}
		}
	}
	{
		raw := query0
		if !queryBound {
			raw = c.Query("q")
		}
		if raw != "" {
			input.Q = raw
		}
	}
	{
		raw := query1
		if !queryBound {
			raw = c.Query("page")
		}
		if raw != "" {
			value, err := strconv.ParseInt(raw, 10, strconv.IntSize)
			if err != nil {
				return reflect.Value{}, kruda.BadRequest("invalid query parameter \"page\": expected int")
			}
			input.Page = int(value)
		}
	}
	return reflect.ValueOf(input).Elem(), nil
}

func makeBindSearchInputValidator(validators []kruda.ValidatorDescriptor) func(*searchInput) bool {
	if len(validators) != 2 {
		return nil
	}
	inputType := reflect.TypeOf((*searchInput)(nil)).Elem()
	// Compiled checks certify that these exact rules have no custom overrides.
	if inputType.NumField() <= 0 || inputType.Field(0).Name != "Q" || inputType.Field(0).Type.Kind() != reflect.String {
		return nil
	}
	if validators[0].Index != 0 || validators[0].OmitEmpty || validators[0].NumElemRules != 0 || len(validators[0].Rules) != 2 || validators[0].NumChecks != 2 {
		return nil
	}
	if validators[0].Rules[0].Name != "min" || validators[0].Rules[0].Param != "1" {
		return nil
	}
	if validators[0].Rules[1].Name != "max" || validators[0].Rules[1].Param != "64" {
		return nil
	}
	if inputType.NumField() <= 1 || inputType.Field(1).Name != "Page" || inputType.Field(1).Type.Kind() != reflect.Int {
		return nil
	}
	if validators[1].Index != 1 || validators[1].OmitEmpty || validators[1].NumElemRules != 0 || len(validators[1].Rules) != 2 || validators[1].NumChecks != 2 {
		return nil
	}
	if validators[1].Rules[0].Name != "min" || validators[1].Rules[0].Param != "1" {
		return nil
	}
	if validators[1].Rules[1].Name != "max" || validators[1].Rules[1].Param != "1000" {
		return nil
	}
	return func(input *searchInput) bool {
		return float64(len(input.Q)) >= 1 && float64(len(input.Q)) <= 64 && int64(input.Page) >= 1 && int64(input.Page) <= 1000
	}
}

var bindSearchInputShape = kruda.BinderShape{NumFields: 2, Fields: []kruda.BinderFieldShape{
	{Name: "Q", Exported: true, Kind: "string", Query: "q", Param: "", Default: "all"},
	{Name: "Page", Exported: true, Kind: "int", Query: "page", Param: "", Default: "1"},
}}

func bindSearchInputAttested() func(*kruda.Ctx) (reflect.Value, error) {
	if !kruda.AttestBinderShape[searchInput](bindSearchInputShape) {
		return nil
	}
	return bindSearchInput
}

func searchInputPlan() kruda.GeneratedPlan[searchInput] {
	return kruda.GeneratedPlan[searchInput]{Shape: bindSearchInputShape, Binder: bindSearchInputAttested(), ValidatorFactory: makeBindSearchInputValidator}
}
